### PR TITLE
Papers

### PR DESCRIPTION
**Pull request by vict0rsch**
Added papers and reorganize.

Thoughts?

What's missing?

Agree with the ordering within categories?

### CODE REVIEW

**Comment by vict0rsch** [comment]
Ping @melisandeteng @sashavor @51N84D @tianyu-z

**Comment by zhangtyu** [comment]
* GAN - [Generative Adversarial Networks](https://arxiv.org/abs/1406.2661) ([github](https://github.com/goodfeli/adversarial))
* CGAN - [Conditional Generative Adversarial Nets](https://arxiv.org/abs/1411.1784) 
* DCGAN - [Unsupervised Representation Learning with Deep Convolutional Generative Adversarial Networks](https://arxiv.org/abs/1511.06434) ([github](https://github.com/Newmu/dcgan_code))
* f-GAN - [f-GAN: Training Generative Neural Samplers using Variational Divergence Minimization](https://arxiv.org/abs/1606.00709) 
* WGAN - [Wasserstein GAN](https://arxiv.org/abs/1701.07875v2) ([github](https://github.com/martinarjovsky/WassersteinGAN))
* pix2pix - [Image-to-Image Translation with Conditional Adversarial Networks](https://arxiv.org/abs/1611.07004) ([github](https://github.com/phillipi/pix2pix))
* pix2pixHD - [High-Resolution Image Synthesis and Semantic Manipulation with Conditional GANs](https://arxiv.org/abs/1711.11585) ([github](https://github.com/NVIDIA/pix2pixHD))
* CycleGAN - [Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks](https://arxiv.org/abs/1703.10593) ([github](https://github.com/junyanz/CycleGAN))
* InstaGAN - [InstaGAN: Instance-aware Image-to-Image Translation](https://arxiv.org/abs/1812.10889)
* UNIT - [Unsupervised Image-to-image Translation Networks](https://arxiv.org/abs/1703.00848) ([github](https://github.com/mingyuliutw/UNIT))
* MUNIT - [Multimodal Unsupervised Image-to-Image Translation](https://arxiv.org/abs/1804.04732)
* SPADE - [Semantic Image Synthesis with Spatially-Adaptive Normalization](https://arxiv.org/abs/1903.07291)
* AdaIN - [Arbitrary Style Transfer in Real-time with Adaptive Instance Normalization](https://arxiv.org/abs/1703.06868)

**Comment by tianyu-z** [comment]
* GAN - [Generative Adversarial Networks](https://arxiv.org/abs/1406.2661) ([github](https://github.com/goodfeli/adversarial))
* CGAN - [Conditional Generative Adversarial Nets](https://arxiv.org/abs/1411.1784) 
* DCGAN - [Unsupervised Representation Learning with Deep Convolutional Generative Adversarial Networks](https://arxiv.org/abs/1511.06434) ([github](https://github.com/Newmu/dcgan_code))
* f-GAN - [f-GAN: Training Generative Neural Samplers using Variational Divergence Minimization](https://arxiv.org/abs/1606.00709) 
* WGAN - [Wasserstein GAN](https://arxiv.org/abs/1701.07875v2) ([github](https://github.com/martinarjovsky/WassersteinGAN))
* pix2pix - [Image-to-Image Translation with Conditional Adversarial Networks](https://arxiv.org/abs/1611.07004) ([github](https://github.com/phillipi/pix2pix))
* pix2pixHD - [High-Resolution Image Synthesis and Semantic Manipulation with Conditional GANs](https://arxiv.org/abs/1711.11585) ([github](https://github.com/NVIDIA/pix2pixHD))
* CycleGAN - [Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks](https://arxiv.org/abs/1703.10593) ([github](https://github.com/junyanz/CycleGAN))
* InstaGAN - [InstaGAN: Instance-aware Image-to-Image Translation](https://arxiv.org/abs/1812.10889)
* UNIT - [Unsupervised Image-to-image Translation Networks](https://arxiv.org/abs/1703.00848) ([github](https://github.com/mingyuliutw/UNIT))
* MUNIT - [Multimodal Unsupervised Image-to-Image Translation](https://arxiv.org/abs/1804.04732)
* SPADE - [Semantic Image Synthesis with Spatially-Adaptive Normalization](https://arxiv.org/abs/1903.07291)
* AdaIN - [Arbitrary Style Transfer in Real-time with Adaptive Instance Normalization](https://arxiv.org/abs/1703.06868)

**Comment by vict0rsch** [comment]
@tianyu-z can you update your comment only with the papers that are not *already* in the PR?

**Comment by vict0rsch** [comment]
great thanks @tianyu-z

**Review by tianyu-z — APPROVED** [review]

**Comment by vict0rsch** [comment]
@sashavor I wanted to wait for the other 2 but nevermind

**Pull request merged**
